--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Dapro718/LevelChangeDimensionScreen
build-by-default: true
branches:
- main
projects:
  LevelChangeDimensionScreen:
    path: ""
...
